import Svg, { ClipPath, Defs, G, LinearGradient, RadialGradient, Rect, Stop, SvgProps } from "react-native-svg";

export function Illustration(props: SvgProps) {
    return (
        <Svg
            width={239}
            height={345}
            viewBox="0 0 239 345"
            fill="none"
            {...props}
        >
            <G
                opacity={0.7}
                filter="url(#filter0_d_4539_22296)"
            >
                <G clipPath="url(#clip0_4539_22296)">
                    <Rect
                        x={-16.4887}
                        y={63.5953}
                        width={187.966}
                        height={301.363}
                        rx={23.2237}
                        fill="url(#paint0_radial_4539_22296)"
                        fillOpacity={0.8}
                    />
                    <Rect
                        x={-16.4887}
                        y={63.5953}
                        width={187.966}
                        height={301.363}
                        rx={23.2237}
                        fill="url(#paint1_radial_4539_22296)"
                        fillOpacity={0.4}
                    />
                    <Rect
                        x={-16.4887}
                        y={63.5953}
                        width={187.966}
                        height={301.363}
                        rx={23.2237}
                        stroke="url(#paint2_radial_4539_22296)"
                        strokeWidth={0.725739}
                    />
                    <G filter="url(#filter1_d_4539_22296)">
                        <Rect
                            x={46.6562}
                            y={68.6758}
                            width={61.6878}
                            height={2.72152}
                            rx={1.36076}
                            fill="white"
                        />
                    </G>
                    <G filter="url(#filter2_d_4539_22296)">
                        <Rect
                            opacity={0.3}
                            width={2.28105}
                            height={12.6525}
                            rx={1.14052}
                            transform="matrix(-1 0 0 1 78.6484 82.2852)"
                            fill="white"
                        />
                        <Rect
                            width={2.28105}
                            height={12.6525}
                            rx={1.14052}
                            transform="matrix(-1 0 0 1 74.0781 82.2852)"
                            fill="white"
                        />
                        <Rect
                            width={2.28105}
                            height={7.84455}
                            rx={1.14052}
                            transform="matrix(-1 0 0 1 78.6484 82.2852)"
                            fill="white"
                        />
                        <Rect
                            width={2.28105}
                            height={12.6525}
                            rx={1.14052}
                            transform="matrix(-1 0 0 1 83.2031 82.2852)"
                            fill="white"
                        />
                    </G>
                    <G filter="url(#filter3_d_4539_22296)">
                        <Rect
                            width={138.798}
                            height={38.1013}
                            rx={7.25739}
                            transform="matrix(-1 0 0 1 133.742 143.973)"
                            fill="url(#paint3_linear_4539_22296)"
                            shape-Rendering="crispEdges"
                        />
                        <Rect
                            x={-0.226794}
                            y={0.226794}
                            width={138.344}
                            height={37.6477}
                            rx={7.0306}
                            transform="matrix(-1 0 0 1 133.289 143.973)"
                            stroke="url(#paint4_linear_4539_22296)"
                            strokeWidth={0.453587}
                            shape-Rendering="crispEdges"
                        />
                        <Rect
                            x={-0.0907174}
                            y={0.0907174}
                            width={101.842}
                            height={3.44726}
                            rx={1.72363}
                            transform="matrix(-1 0 0 1 126.303 151.23)"
                            fill="url(#paint5_linear_4539_22296)"
                        />
                        <Rect
                            x={-0.0907174}
                            y={0.0907174}
                            width={101.842}
                            height={3.44726}
                            rx={1.72363}
                            transform="matrix(-1 0 0 1 126.303 151.23)"
                            stroke="url(#paint6_linear_4539_22296)"
                            strokeWidth={0.181435}
                        />
                        <Rect
                            x={-0.0907174}
                            y={0.0907174}
                            width={123.174}
                            height={3.44726}
                            rx={1.72363}
                            transform="matrix(-1 0 0 1 125.373 160.756)"
                            fill="url(#paint7_linear_4539_22296)"
                        />
                        <Rect
                            x={-0.0907174}
                            y={0.0907174}
                            width={123.174}
                            height={3.44726}
                            rx={1.72363}
                            transform="matrix(-1 0 0 1 125.373 160.756)"
                            stroke="url(#paint8_linear_4539_22296)"
                            strokeWidth={0.181435}
                        />
                    </G>
                    <G filter="url(#filter4_d_4539_22296)">
                        <Rect
                            width={138.798}
                            height={38.1013}
                            rx={7.25739}
                            transform="matrix(-1 0 0 1 162.773 231.061)"
                            fill="url(#paint9_linear_4539_22296)"
                            shape-Rendering="crispEdges"
                        />
                        <Rect
                            x={-0.226794}
                            y={0.226794}
                            width={138.344}
                            height={37.6477}
                            rx={7.0306}
                            transform="matrix(-1 0 0 1 162.32 231.061)"
                            stroke="url(#paint10_linear_4539_22296)"
                            strokeWidth={0.453587}
                            shape-Rendering="crispEdges"
                        />
                        <Rect
                            x={-0.0907174}
                            y={0.0907174}
                            width={93.2575}
                            height={3.44726}
                            rx={1.72363}
                            transform="matrix(-1 0 0 1 155.334 238.318)"
                            fill="url(#paint11_linear_4539_22296)"
                        />
                        <Rect
                            x={-0.0907174}
                            y={0.0907174}
                            width={93.2575}
                            height={3.44726}
                            rx={1.72363}
                            transform="matrix(-1 0 0 1 155.334 238.318)"
                            stroke="url(#paint12_linear_4539_22296)"
                            strokeWidth={0.181435}
                        />
                        <Rect
                            x={-0.0907174}
                            y={0.0907174}
                            width={124.101}
                            height={3.44726}
                            rx={1.72363}
                            transform="matrix(-1 0 0 1 155.334 247.391)"
                            fill="url(#paint13_linear_4539_22296)"
                        />
                        <Rect
                            x={-0.0907174}
                            y={0.0907174}
                            width={124.101}
                            height={3.44726}
                            rx={1.72363}
                            transform="matrix(-1 0 0 1 155.334 247.391)"
                            stroke="url(#paint14_linear_4539_22296)"
                            strokeWidth={0.181435}
                        />
                    </G>
                    <G filter="url(#filter5_dd_4539_22296)">
                        <G clipPath="url(#clip1_4539_22296)">
                            <Rect
                                width={138.798}
                                height={38.1013}
                                rx={7.25739}
                                transform="matrix(-1 0 0 1 162.773 275.512)"
                                fill="url(#paint15_linear_4539_22296)"
                                shape-Rendering="crispEdges"
                            />
                            <G opacity={0.4}>
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={101.842}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 282.77)"
                                    fill="url(#paint16_linear_4539_22296)"
                                />
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={101.842}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 282.77)"
                                    stroke="url(#paint17_linear_4539_22296)"
                                    strokeWidth={0.181435}
                                />
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={123.173}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 291.842)"
                                    fill="url(#paint18_linear_4539_22296)"
                                />
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={123.173}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 291.842)"
                                    stroke="url(#paint19_linear_4539_22296)"
                                    strokeWidth={0.181435}
                                />
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={123.173}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 300.912)"
                                    fill="url(#paint20_linear_4539_22296)"
                                />
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={123.173}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 300.912)"
                                    stroke="url(#paint21_linear_4539_22296)"
                                    strokeWidth={0.181435}
                                />
                            </G>
                            <G filter="url(#filter6_f_4539_22296)">
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={101.842}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 282.77)"
                                    fill="url(#paint22_linear_4539_22296)"
                                />
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={101.842}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 282.77)"
                                    stroke="url(#paint23_linear_4539_22296)"
                                    strokeWidth={0.181435}
                                />
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={123.173}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 291.842)"
                                    fill="url(#paint24_linear_4539_22296)"
                                />
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={123.173}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 291.842)"
                                    stroke="url(#paint25_linear_4539_22296)"
                                    strokeWidth={0.181435}
                                />
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={123.173}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 300.912)"
                                    fill="url(#paint26_linear_4539_22296)"
                                />
                                <Rect
                                    x={-0.0907174}
                                    y={0.0907174}
                                    width={123.173}
                                    height={3.44726}
                                    rx={1.72363}
                                    transform="matrix(-1 0 0 1 155.334 300.912)"
                                    stroke="url(#paint27_linear_4539_22296)"
                                    strokeWidth={0.181435}
                                />
                            </G>
                        </G>
                        <Rect
                            x={-0.226794}
                            y={0.226794}
                            width={138.344}
                            height={37.6477}
                            rx={7.0306}
                            transform="matrix(-1 0 0 1 162.32 275.512)"
                            stroke="url(#paint28_linear_4539_22296)"
                            strokeWidth={0.453587}
                            shape-Rendering="crispEdges"
                        />
                    </G>
                    <G filter="url(#filter7_dd_4539_22296)">
                        <Rect
                            x={4.92188}
                            y={191.146}
                            width={154.22}
                            height={27.2152}
                            rx={7.25739}
                            fill="url(#paint29_linear_4539_22296)"
                            shape-Rendering="crispEdges"
                        />
                        <Rect
                            x={5.14867}
                            y={191.373}
                            width={153.766}
                            height={26.7616}
                            rx={7.0306}
                            stroke="url(#paint30_linear_4539_22296)"
                            strokeWidth={0.453587}
                            shape-Rendering="crispEdges"
                        />
                        <Rect
                            x={21.25}
                            y={198.404}
                            width={121.561}
                            height={6.23859}
                            rx={3.1193}
                            fill="url(#paint31_linear_4539_22296)"
                        />
                    </G>
                </G>
                <Rect
                    x={-19.2074}
                    y={60.8746}
                    width={193.41}
                    height={306.806}
                    rx={25.038}
                    stroke="url(#paint32_linear_4539_22296)"
                    strokeWidth={0.725739}
                    shape-Rendering="crispEdges"
                />
            </G>
            <Defs>
                <RadialGradient
                    id="paint0_radial_4539_22296"
                    cx={0}
                    cy={0}
                    r={1}
                    gradientUnits="userSpaceOnUse"
                    gradientTransform="translate(171.143 38.1012) rotate(109.908) scale(310.102 193.698)"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.84}
                    />
                    <Stop
                        offset={0.446331}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </RadialGradient>
                <RadialGradient
                    id="paint1_radial_4539_22296"
                    cx={0}
                    cy={0}
                    r={1}
                    gradientUnits="userSpaceOnUse"
                    gradientTransform="translate(-17.8784 215.391) scale(133.836 83.5974)"
                >
                    <Stop stopColor="white" />
                    <Stop
                        offset={0.786458}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </RadialGradient>
                <RadialGradient
                    id="paint2_radial_4539_22296"
                    cx={0}
                    cy={0}
                    r={1}
                    gradientUnits="userSpaceOnUse"
                    gradientTransform="translate(159.846 68.084) rotate(119.999) scale(376.314 235.055)"
                >
                    <Stop stopColor="white" />
                    <Stop
                        offset={0.264031}
                        stopColor="white"
                        stopOpacity={0}
                    />
                    <Stop
                        offset={0.59375}
                        stopColor="white"
                        stopOpacity={0.17}
                    />
                    <Stop
                        offset={0.992413}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </RadialGradient>
                <LinearGradient
                    id="paint3_linear_4539_22296"
                    x1={94.6078}
                    y1={-36.8554}
                    x2={67.3649}
                    y2={43.0296}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop stopColor="white" />
                    <Stop
                        offset={0.883161}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint4_linear_4539_22296"
                    x1={69.3988}
                    y1={0}
                    x2={69.3988}
                    y2={38.1013}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop stopColor="white" />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint5_linear_4539_22296"
                    x1={0.034764}
                    y1={3.62871}
                    x2={74.497}
                    y2={3.62871}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.6}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint6_linear_4539_22296"
                    x1={51.0116}
                    y1={0}
                    x2={51.0116}
                    y2={3.6287}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.46}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint7_linear_4539_22296"
                    x1={0.0420328}
                    y1={3.62871}
                    x2={90.0737}
                    y2={3.62871}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.6}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint8_linear_4539_22296"
                    x1={61.6777}
                    y1={0}
                    x2={61.6777}
                    y2={3.6287}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.46}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint9_linear_4539_22296"
                    x1={50.9215}
                    y1={-24.3977}
                    x2={58.5003}
                    y2={46.2698}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop stopColor="white" />
                    <Stop
                        offset={0.690361}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint10_linear_4539_22296"
                    x1={69.3988}
                    y1={0}
                    x2={69.3988}
                    y2={38.1013}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop stopColor="white" />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint11_linear_4539_22296"
                    x1={0.0318389}
                    y1={3.62871}
                    x2={68.2288}
                    y2={3.62871}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0}
                    />
                    <Stop
                        offset={0.869792}
                        stopColor="white"
                        stopOpacity={0.6}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0.29}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint12_linear_4539_22296"
                    x1={46.7195}
                    y1={0}
                    x2={46.7195}
                    y2={3.6287}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.46}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint13_linear_4539_22296"
                    x1={0.0423488}
                    y1={3.62871}
                    x2={90.7509}
                    y2={3.62871}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0}
                    />
                    <Stop
                        offset={0.869792}
                        stopColor="white"
                        stopOpacity={0.6}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0.29}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint14_linear_4539_22296"
                    x1={62.1414}
                    y1={0}
                    x2={62.1414}
                    y2={3.6287}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.46}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint15_linear_4539_22296"
                    x1={50.9215}
                    y1={-24.3977}
                    x2={58.5003}
                    y2={46.2698}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop stopColor="white" />
                    <Stop
                        offset={0.690361}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint16_linear_4539_22296"
                    x1={0.034764}
                    y1={3.62871}
                    x2={74.497}
                    y2={3.62871}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0}
                    />
                    <Stop
                        offset={0.869792}
                        stopColor="white"
                        stopOpacity={0.6}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0.29}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint17_linear_4539_22296"
                    x1={51.0116}
                    y1={0}
                    x2={51.0116}
                    y2={3.6287}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.46}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint18_linear_4539_22296"
                    x1={0.0420325}
                    y1={3.62871}
                    x2={90.073}
                    y2={3.62871}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0}
                    />
                    <Stop
                        offset={0.869792}
                        stopColor="white"
                        stopOpacity={0.6}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0.29}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint19_linear_4539_22296"
                    x1={61.6772}
                    y1={0}
                    x2={61.6772}
                    y2={3.6287}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.46}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint20_linear_4539_22296"
                    x1={0.0420325}
                    y1={3.62871}
                    x2={90.073}
                    y2={3.62871}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0.42}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint21_linear_4539_22296"
                    x1={61.6772}
                    y1={0}
                    x2={61.6772}
                    y2={3.6287}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.46}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint22_linear_4539_22296"
                    x1={0.034764}
                    y1={3.62871}
                    x2={74.497}
                    y2={3.62871}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0}
                    />
                    <Stop
                        offset={0.869792}
                        stopColor="white"
                        stopOpacity={0.6}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0.29}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint23_linear_4539_22296"
                    x1={51.0116}
                    y1={0}
                    x2={51.0116}
                    y2={3.6287}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.46}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint24_linear_4539_22296"
                    x1={0.0420325}
                    y1={3.62871}
                    x2={90.073}
                    y2={3.62871}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0}
                    />
                    <Stop
                        offset={0.869792}
                        stopColor="white"
                        stopOpacity={0.6}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0.29}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint25_linear_4539_22296"
                    x1={61.6772}
                    y1={0}
                    x2={61.6772}
                    y2={3.6287}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.46}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint26_linear_4539_22296"
                    x1={0.0420325}
                    y1={3.62871}
                    x2={90.073}
                    y2={3.62871}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0.42}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint27_linear_4539_22296"
                    x1={61.6772}
                    y1={0}
                    x2={61.6772}
                    y2={3.6287}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        stopColor="white"
                        stopOpacity={0.46}
                    />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint28_linear_4539_22296"
                    x1={69.3988}
                    y1={0}
                    x2={69.3988}
                    y2={38.1013}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop stopColor="white" />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint29_linear_4539_22296"
                    x1={61.5013}
                    y1={173.72}
                    x2={65.0047}
                    y2={224.535}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop stopColor="white" />
                    <Stop
                        offset={0.690361}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint30_linear_4539_22296"
                    x1={82.0317}
                    y1={191.146}
                    x2={82.0317}
                    y2={218.362}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop stopColor="white" />
                    <Stop
                        offset={1}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint31_linear_4539_22296"
                    x1={61.6635}
                    y1={178.196}
                    x2={63.0973}
                    y2={209.74}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        offset={0.412666}
                        stopColor="white"
                    />
                    <Stop
                        offset={0.848601}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <LinearGradient
                    id="paint32_linear_4539_22296"
                    x1={73.8915}
                    y1={-282.486}
                    x2={78.4347}
                    y2={399.353}
                    gradientUnits="userSpaceOnUse"
                >
                    <Stop
                        offset={0.208333}
                        stopColor="white"
                    />
                    <Stop
                        offset={0.932292}
                        stopColor="white"
                        stopOpacity={0}
                    />
                </LinearGradient>
                <ClipPath id="clip0_4539_22296">
                    <Rect
                        x={-19.5703}
                        y={60.5117}
                        width={194.135}
                        height={307.532}
                        rx={25.4009}
                        fill="white"
                    />
                </ClipPath>
                <ClipPath id="clip1_4539_22296">
                    <Rect
                        width={138.798}
                        height={38.1013}
                        rx={7.25739}
                        transform="matrix(-1 0 0 1 162.773 275.512)"
                        fill="white"
                    />
                </ClipPath>
            </Defs>
        </Svg>
    );
}